### ISSUE TITLE
Hide scratchpad if called again an exclusion command

### ISSUE THREAD

**Issue by AnderRasoVazquez** [cornerman/i3-select-scratchpad#1]
If I use this command it will show scratchpad and exclude my telegram window:
`select-scratchpad.rb -i "(?i)telegram" -n`

If I want to hide this window I can't use the same command I must use:
`select-scratchpad.rb`

**If I could use the first command to hide the scratchpad too I could have one key binding instead of two.**

Keep up the good work! =)

**Comment by cornerman** [comment]
This was done on purpose in order to emulate the behavior of `scratchpad show` with a subset of the scratchpad windows. So, if a matching scratchpad window is visible on any workspace it will be moved to the current workspace and is focused. If it is already focused it will be hidden. All other scratchpad windows are ignored.

We could add an option for not applying the filter on visible scratchpad windows. What do you think? Maybe something like this (not sure about the option name though):

`select-scratchpad.rb -i "(?i)telegram" -n --any-visible`

**Comment by cornerman** [comment]
Ok, I have added the option as described above. You should be able to enable it by adding `--any-visible` or `-a` to the command. Let me know if this is covering your use case.

**Comment by AnderRasoVazquez** [comment]
Now it doesn't hide any window. Calling the command without arguments shows a window but calling it again it doesn't hide it. `-a` doesn't work neither.

**Comment by cornerman** [comment]
> Calling the command without arguments shows a window but calling it again it doesn't hide it

Are you focusing the scratchpad window when issuing the command the second time?

**Comment by AnderRasoVazquez** [comment]
These two commands don't hide any window for me:
- `./select-scratchpad.rb -a -i "(?i)telegram" -n`
- `./select-scratchpad.rb`

**Comment by cornerman** [comment]
Does it work with `i3-msg scratchpad show`?

Be aware: The windows are only hidden, if they were send to scratchpad before.

**Comment by AnderRasoVazquez** [comment]
`i3-msg scratchpad show` doesn't work neither. That's weird because on my config `bindsym $mod+minus scratchpad show` works.

**Comment by cornerman** [comment]
So, the keybinding works but i3-msg in terminal does not? that is indeed weird, should be the same behaviour. Are you focusing the same window when using i3-msg and your keybinding?

**Comment by AnderRasoVazquez** [comment]
Sorry @cornerman ALL works. I was testing it from the terminal and I was focusing the terminal instead the scratchpad. The command works perfectly =)

**Comment by cornerman** [comment]
No problem. Glad it works :)
